
SRC		= megaphone.cpp

NAME 	= megaphone

COMP 	= c++
CXXFLAGS 	= -Wall -Wextra -Werror
OPTIONS	= -std=c++98

all:
	${COMP} ${CXXFLAGS} ${OPTIONS} -o ${NAME} ${SRC}

clean:
	rm -rf ${NAME}

re: clean all
